3 Value (non_rec, @., [ ((t0, [ ], [ ], Type (unit)), Constructor (3, tt)) ])

5
Value
  (non_rec, @.,
    [
      ((t1, [ ], [ ], (Type (ascii) * Type (string))),
        Tuple (5, Constant (5, Char("c")), Constant (5, String("one"))))
    ])

7
Value
  (non_rec, @.,
    [
      ((t2, [ ], [ ],
        (Type (Z) * Type (Z) * Type (Z) * Type (bool) * Type (bool))),
        Tuple
          (7, Constant (7, Int(1)), Constant (7, Int(2)),
            Constant (7, Int(3)), Constructor (7, false),
            Constructor (7, true)))
    ])

9
Value
  (non_rec, @.,
    [
      ((f, [ A ], [ (x, A) ], (A * A)),
        Tuple (9, Variable (9, x), Variable (9, x)))
    ])

11
Value
  (non_rec, @.,
    [
      ((t3, [ ], [ ], (Type (Z) * Type (Z))),
        Apply (11, Variable (11, f), [ Constant (11, Int(12)) ]))
    ])
