3 Value (non_rec, @., [ ((u, [ ], [ ], Type (unit)), Constructor (3, tt)) ])

5
Value (non_rec, @., [ ((l1, [ A ], [ ], Type (list, A)), Constructor (5, [])) ])

7
Value
  (non_rec, @.,
    [
      ((l2, [ ], [ ], Type (list, Type (Z))),
        Constructor (7, cons, Constant (7, Int(1)), Constructor (7, [])))
    ])

9
Value
  (non_rec, @.,
    [
      ((l3, [ ], [ ], Type (list, Type (Z))),
        Constructor
          (9, cons, Constant (9, Int(1)),
            Constructor
              (9, cons, Constant (9, Int(5)),
                Constructor
                  (9, cons, Constant (9, Int(7)),
                    Constructor
                      (9, cons, Constant (9, Int(32)),
                        Constructor
                          (9, cons, Constant (9, Int(15)),
                            Constructor (9, [])))))))
    ])

11
Value
  (non_rec, @., [ ((o1, [ A ], [ ], Type (option, A)), Constructor (11, None)) ])

13
Value
  (non_rec, @.,
    [
      ((o2, [ ], [ ], Type (option, Type (Z))),
        Constructor (13, Some, Constant (13, Int(12))))
    ])

15
Value (non_rec, @., [ ((c, [ ], [ ], Type (ascii)), Constant (15, Char("g"))) ])

17
Value
  (non_rec, @.,
    [ ((s1, [ ], [ ], Type (string)), Constant (17, String("bla"))) ])

19
Value
  (non_rec, @., [ ((s2, [ ], [ ], Type (string)), Constant (19, String("\""))) ])
