3
Value
  (non_rec, @.,
    [
      ((n, [ ], [ ], Type (Z/3)),
        Match
          (3,
            Tuple
              (3,
                Constructor
                  (3, cons/3, Constant (3, Int(1)),
                    Constructor
                      (3, cons/3, Constant (3, Int(2)),
                        Constructor (3, []/3))),
                Constructor (3, false/3)),
            [
              (Tuple
                (Constructor
                  (cons/3, x,
                    Constructor
                      (cons/3,
                        Any,
                        Constructor
                          ([]/3))),
                  Constructor (true/3)),
                Variable (4, x/0));
              (Tuple
                (Constructor
                  (cons/3, Any,
                    Constructor
                      (cons/3,
                        y,
                        Constructor
                          ([]/3))),
                  Constructor (false/3)),
                Variable (5, y/0));
              (Any, Constant (6, Int(0)))
            ]))
    ])
