3
Value
  (rec, @.,
    [
      ((map_rec, [ A; B ],
        [ (counter, Type (nat)); (f, (A -> B)); (l, Type (list, A)) ],
        Type (list, B)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (4, Variable (4, l),
                    [
                      (Constructor
                        ([]),
                        Constructor
                          (5,
                            []));
                      (Constructor
                        (cons,
                          x,
                          xs),
                        Constructor
                          (6,
                            cons,
                            Apply
                              (6,
                                Variable
                                  (6,
                                    f),
                                [
                                  Variable
                                    (6,
                                      x)
                                ]),
                            Apply
                              (6,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        map_rec),
                                    [
                                      Variable
                                        (?,
                                          counter)
                                    ]),
                                [
                                  Variable
                                    (6,
                                      f);
                                  Variable
                                    (6,
                                      xs)
                                ])))
                    ]))
            ]))
    ])

3
Value
  (non_rec, @.,
    [
      ((map, [ A; B ], [ (f, (A -> B)); (l, Type (list, A)) ], Type (list, B)),
        Apply
          (?, Variable (?, map_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, f);
              Variable (?, l)
            ]))
    ])

8
Value
  (rec, @.,
    [
      ((fold_rec, [ A; B ],
        [
          (counter, Type (nat));
          (f, (A -> (B -> A)));
          (a, A);
          (l, Type (list, B))
        ], A),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (9, Variable (9, l),
                    [
                      (Constructor
                        ([]),
                        Variable
                          (10,
                            a));
                      (Constructor
                        (cons,
                          x,
                          xs),
                        Apply
                          (11,
                            Apply
                              (?,
                                Variable
                                  (?,
                                    fold_rec),
                                [
                                  Variable
                                    (?,
                                      counter)
                                ]),
                            [
                              Variable
                                (11,
                                  f);
                              Apply
                                (11,
                                  Variable
                                    (11,
                                      f),
                                  [
                                    Variable
                                      (11,
                                        a);
                                    Variable
                                      (11,
                                        x)
                                  ]);
                              Variable
                                (11,
                                  xs)
                            ]))
                    ]))
            ]))
    ])

8
Value
  (non_rec, @.,
    [
      ((fold, [ A; B ], [ (f, (A -> (B -> A))); (a, A); (l, Type (list, B)) ], A),
        Apply
          (?, Variable (?, fold_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, f);
              Variable (?, a);
              Variable (?, l)
            ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((l, [ ], [ ], Type (list, Type (Z))),
        Constructor
          (13, cons, Constant (13, Int(5)),
            Constructor
              (13, cons, Constant (13, Int(6)),
                Constructor
                  (13, cons, Constant (13, Int(7)),
                    Constructor
                      (13, cons, Constant (13, Int(2)),
                        Constructor (13, []))))))
    ])

15
Value
  (non_rec, @.,
    [
      ((n, [ A ],
        [ (incr, (Type (Z) -> A)); (plus, (Type (Z) -> (A -> Type (Z)))) ],
        Type (Z)),
        Apply
          (16, Variable (16, fold),
            [
              Function
                (16, x,
                  Function
                    (16,
                      y,
                      Apply
                        (16,
                          Variable
                            (16,
                              plus),
                          [
                            Variable
                              (16,
                                x);
                            Variable
                              (16,
                                y)
                          ])));
              Constant (16, Int(0));
              Apply
                (16, Variable (16, map),
                  [
                    Variable
                      (16,
                        incr);
                    Variable
                      (16,
                        l)
                  ])
            ]))
    ])
