3
Value
  (non_rec, @.,
    [
      ((b, [ ], [ ], Type (bool/3)),
        Apply
          (3, Variable (3, orb/3),
            [
              Apply
                (3, Variable (3, equiv_decb/3),
                  [
                    Constructor
                      (3,
                        false/3);
                    Constructor
                      (3,
                        true/3)
                  ]);
              Apply
                (3, Variable (3, andb/3),
                  [
                    Apply
                      (3,
                        Variable
                          (3,
                            nequiv_decb/3),
                        [
                          Constructor
                            (3,
                              tt/3);
                          Constructor
                            (3,
                              tt/3)
                        ]);
                    Apply
                      (3,
                        Variable
                          (3,
                            negb/3),
                        [
                          Constructor
                            (3,
                              true/3)
                        ])
                  ])
            ]))
    ])

5
Value
  (non_rec, @.,
    [
      ((n1, [ ], [ ], Type (Z/3)),
        Apply
          (5, Variable (5, Z.add/3),
            [
              Constant (5, Int(1));
              Apply
                (5, Variable (5, Z.mul/3),
                  [
                    Constant
                      (5,
                        Int(2));
                    Constant
                      (5,
                        Int(3))
                  ])
            ]))
    ])

7
Value
  (non_rec, @.,
    [
      ((n2, [ ], [ ], Type (Z/3)),
        Apply
          (7, Variable (7, Z.sub/3),
            [
              Apply
                (7, Variable (7, Z.add/3),
                  [
                    Apply
                      (7,
                        Variable
                          (7,
                            Z.abs/3),
                        [
                          Constant
                            (7,
                              Int(-1))
                        ]);
                    Constant
                      (7,
                        Int(1))
                  ]);
              Apply
                (7, Variable (7, Z.mul/3),
                  [
                    Apply
                      (7,
                        Variable
                          (7,
                            Z.modulo/3),
                        [
                          Apply
                            (7,
                              Variable
                                (7,
                                  Z.div/3),
                              [
                                Constant
                                  (7,
                                    Int(5));
                                Constant
                                  (7,
                                    Int(23))
                              ]);
                          Constant
                            (7,
                              Int(4))
                        ]);
                    Constant
                      (7,
                        Int(3))
                  ])
            ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((n3, [ ], [ ], Type (Z/3)),
        Apply
          (9, Variable (9, Z.pred/3),
            [
              Apply
                (9, Variable (9, Z.succ/3),
                  [
                    Constant
                      (9,
                        Int(12))
                  ])
            ]))
    ])

11
Value
  (non_rec, @.,
    [
      ((n4, [ ], [ ], Type (Z/3)),
        Apply
          (11, Variable (11, Z.lxor/3),
            [
              Apply
                (11, Variable (11, Z.lor/3),
                  [
                    Apply
                      (11,
                        Variable
                          (11,
                            Z.land/3),
                        [
                          Constant
                            (11,
                              Int(5));
                          Constant
                            (11,
                              Int(7))
                        ]);
                    Constant
                      (11,
                        Int(3))
                  ]);
              Constant (11, Int(9))
            ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((n5, [ ], [ ], Type (Z/3)),
        Apply
          (13, Variable (13, Z.add/3),
            [
              Apply
                (13, Variable (13, Z.shiftl/3),
                  [
                    Constant
                      (13,
                        Int(156));
                    Constant
                      (13,
                        Int(4))
                  ]);
              Apply
                (13, Variable (13, Z.shiftr/3),
                  [
                    Constant
                      (13,
                        Int(12));
                    Constant
                      (13,
                        Int(1))
                  ])
            ]))
    ])

15
Value
  (non_rec, @.,
    [
      ((s, [ ], [ ], Type (string/3)),
        Apply
          (15, Variable (15, String.append/3),
            [ Constant (15, String("ghj")); Constant (15, String("klm")) ]))
    ])

17
Value
  (non_rec, @.,
    [
      ((c, [ A ], [ (x, A) ], Type (ascii/3)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (17,
                    Variable
                      (17,
                        OCaml.Pervasives.char_of_int/3),
                    [
                      Apply
                        (17,
                          Variable
                            (17,
                              Z.add/3),
                          [
                            Apply
                              (17,
                                Variable
                                  (17,
                                    OCaml.Pervasives.int_of_char/3),
                                [
                                  Constant
                                    (17,
                                      Char("c"))
                                ]);
                            Constant
                              (17,
                                Int(1))
                          ])
                    ]))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((x, [ ], [ ], Type (unit/3)),
        Apply
          (19, Variable (19, OCaml.Pervasives.ignore/3),
            [ Constant (19, Int(23)) ]))
    ])

21
Value
  (non_rec, @.,
    [
      ((p, [ ], [ ], Type (Z/3)),
        Apply
          (21, Variable (21, Z.add/3),
            [
              Apply
                (21, Variable (21, fst/3),
                  [
                    Tuple
                      (21,
                        Constant
                          (21,
                            Int(1)),
                        Constant
                          (21,
                            Int(2)))
                  ]);
              Apply
                (21, Variable (21, snd/3),
                  [
                    Tuple
                      (21,
                        Constant
                          (21,
                            Int(3)),
                        Constant
                          (21,
                            Int(4)))
                  ])
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((l, [ ], [ ], Type (list/3, Type (Z/3))),
        Apply
          (23, Variable (23, OCaml.Pervasives.app/3),
            [
              Constructor
                (23, cons/3, Constant (23, Int(1)),
                  Constructor
                    (23,
                      cons/3,
                      Constant
                        (23,
                          Int(2)),
                      Constructor
                        (23,
                          []/3)));
              Constructor
                (23, cons/3, Constant (23, Int(3)),
                  Constructor (23, []/3))
            ]))
    ])

25
Value
  (non_rec, @.,
    [
      ((y, [ ], [ ], Type (Z/3)),
        Apply
          (25, Variable (25, apply/3),
            [
              Function
                (25, n,
                  Apply
                    (25,
                      Variable
                        (25,
                          Z.add/3),
                      [
                        Variable
                          (25,
                            n/0);
                        Constant
                          (25,
                            Int(1))
                      ]));
              Constant (25, Int(12))
            ]))
    ])
