3
Inductive t1:
  ([ ], [ (C1, [ Type (Z) ]); (C2, [ Type (bool); Type (Z) ]); (C3, [ ]) ])

8
Value
  (non_rec, @.,
    [
      ((n, [ ], [ ], Type (t1)),
        Constructor (8, C2, Constructor (8, false), Constant (8, Int(3))))
    ])

10
Value
  (non_rec, @.,
    [
      ((m, [ ], [ ], Type (bool)),
        Match
          (10, Variable (10, n),
            [
              (Constructor (C2, b, Any), Variable (11, b));
              (Any, Constructor (12, true))
            ]))
    ])

14
Inductive t2:
  ([ a ], [ (D1, [ ]); (D2, [ a; Type (t2, a) ]) ])

18
Value
  (rec, @.,
    [
      ((of_list_rec, [ A ], [ (counter, Type (nat)); (l, Type (list, A)) ],
        Type (t2, A)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (19, Variable (19, l),
                    [
                      (Constructor
                        ([]),
                        Constructor
                          (20,
                            D1));
                      (Constructor
                        (cons,
                          x,
                          xs),
                        Constructor
                          (21,
                            D2,
                            Variable
                              (21,
                                x),
                            Apply
                              (21,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        of_list_rec),
                                    [
                                      Variable
                                        (?,
                                          counter)
                                    ]),
                                [
                                  Variable
                                    (21,
                                      xs)
                                ])))
                    ]))
            ]))
    ])

18
Value
  (non_rec, @.,
    [
      ((of_list, [ A ], [ (l, Type (list, A)) ], Type (t2, A)),
        Apply
          (?, Variable (?, of_list_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, l)
            ]))
    ])

23
Value
  (rec, @.,
    [
      ((sum_rec, [ ], [ (counter, Type (nat)); (l, Type (t2, Type (Z))) ],
        Type (Z)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (24, Variable (24, l),
                    [
                      (Constructor
                        (D1),
                        Constant
                          (25,
                            Int(0)));
                      (Constructor
                        (D2,
                          x,
                          xs),
                        Apply
                          (26,
                            Variable
                              (26,
                                Z.add),
                            [
                              Variable
                                (26,
                                  x);
                              Apply
                                (26,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          sum_rec),
                                      [
                                        Variable
                                          (?,
                                            counter)
                                      ]),
                                  [
                                    Variable
                                      (26,
                                        xs)
                                  ])
                            ]))
                    ]))
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((sum (= sum_1), [ ], [ (l, Type (t2, Type (Z))) ], Type (Z)),
        Apply
          (?, Variable (?, sum_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, l)
            ]))
    ])

28
Value
  (non_rec, @.,
    [
      ((s, [ A ], [ (x, A) ], Type (Z)),
        Match
          (?, Variable (?, x),
            [
              (Any,
                Apply
                  (28,
                    Variable
                      (28,
                        sum_1),
                    [
                      Apply
                        (28,
                          Variable
                            (28,
                              of_list),
                          [
                            Constructor
                              (28,
                                cons,
                                Constant
                                  (28,
                                    Int(5)),
                                Constructor
                                  (28,
                                    cons,
                                    Constant
                                      (28,
                                        Int(7)),
                                    Constructor
                                      (28,
                                        cons,
                                        Constant
                                          (28,
                                            Int(3)),
                                        Constructor
                                          (28,
                                            []))))
                          ])
                    ]))
            ]))
    ])

30 Abstract (t3, [ ])

31 Abstract (t4, [ a ])

32
Inductive t5:
  ([ ], [ (C, [ ]) ])
