3 Module List2:
  4
  Inductive t:
    ([ a ], [ (Nil, [ ]); (Cons, [ a; Type (t/0, a) ]) ])
  
  8
  Value
    (rec, @.,
      [
        ((sum_rec, [ ],
          [ (counter, Type (nat/4)); (l, Type (t/0, Type (Z/4))) ],
          Type (Z/4)),
          Match
            (?, Variable (?, counter/0),
              [
                (Constructor (O/4),
                  Apply
                    (?,
                      Variable
                        (?,
                          not_terminated/4),
                      [
                        Tuple
                          (?)
                      ]));
                (Constructor (S/4, counter),
                  Match
                    (9,
                      Variable
                        (9,
                          l/0),
                      [
                        (Constructor
                          (Nil/0),
                          Constant
                            (10,
                              Int(0)));
                        (Constructor
                          (Cons/0,
                            x,
                            xs),
                          Apply
                            (11,
                              Variable
                                (11,
                                  Z.add/4),
                              [
                                Variable
                                  (11,
                                    x/0);
                                Apply
                                  (11,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            sum_rec/0),
                                        [
                                          Variable
                                            (?,
                                              counter/0)
                                        ]),
                                    [
                                      Variable
                                        (11,
                                          xs/0)
                                    ])
                              ]))
                      ]))
              ]))
      ])
  
  8
  Value
    (non_rec, @.,
      [
        ((sum, [ ], [ (l, Type (t/0, Type (Z/4))) ], Type (Z/4)),
          Apply
            (?, Variable (?, sum_rec/0),
              [
                Apply
                  (?,
                    Variable
                      (?,
                        read_counter/4),
                    [
                      Tuple
                        (?)
                    ]);
                Variable (?, l/0)
              ]))
      ])
  
  13
  Value
    (rec, @.,
      [
        ((of_list_rec, [ A ],
          [ (counter, Type (nat/4)); (x, Type (list/4, A)) ], Type (t/0, A)),
          Match
            (?, Variable (?, counter/0),
              [
                (Constructor (O/4),
                  Apply
                    (?,
                      Variable
                        (?,
                          not_terminated/4),
                      [
                        Tuple
                          (?)
                      ]));
                (Constructor (S/4, counter),
                  Match
                    (?,
                      Variable
                        (?,
                          x/0),
                      [
                        (Constructor
                          ([]/4),
                          Constructor
                            (14,
                              Nil/0));
                        (Constructor
                          (cons/4,
                            x,
                            xs),
                          Constructor
                            (15,
                              Cons/0,
                              Variable
                                (15,
                                  x/0),
                              Apply
                                (15,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          of_list_rec/0),
                                      [
                                        Variable
                                          (?,
                                            counter/0)
                                      ]),
                                  [
                                    Variable
                                      (15,
                                        xs/0)
                                  ])))
                      ]))
              ]))
      ])
  
  13
  Value
    (non_rec, @.,
      [
        ((of_list, [ A ], [ (x, Type (list/4, A)) ], Type (t/0, A)),
          Apply
            (?, Variable (?, of_list_rec/0),
              [
                Apply
                  (?,
                    Variable
                      (?,
                        read_counter/4),
                    [
                      Tuple
                        (?)
                    ]);
                Variable (?, x/0)
              ]))
      ])
  
  17 Module Inside:
    18
    Value (non_rec, @., [ ((x, [ ], [ ], Type (Z/5)), Constant (18, Int(12))) ])

22
Value
  (non_rec, @.,
    [
      ((n, [ A ], [ (x, A) ], Type (Z/3)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (22,
                    Variable
                      (22,
                        List2.sum/0),
                    [
                      Apply
                        (22,
                          Variable
                            (22,
                              List2.of_list/0),
                          [
                            Constructor
                              (22,
                                cons/3,
                                Constant
                                  (22,
                                    Int(5)),
                                Constructor
                                  (22,
                                    cons/3,
                                    Constant
                                      (22,
                                        Int(7)),
                                    Constructor
                                      (22,
                                        cons/3,
                                        Constant
                                          (22,
                                            Int(6)),
                                        Constructor
                                          (22,
                                            cons/3,
                                            Variable
                                              (22,
                                                List2.Inside.x/0),
                                            Constructor
                                              (22,
                                                []/3)))))
                          ])
                    ]))
            ]))
    ])
