3 Module List2:
  4
  Inductive t:
    ([ a ], [ (Nil, [ ]); (Cons, [ a; Type (Ex10.List2/t, a) ]) ])
  
  8
  Value
    (rec, @.,
      [
        ((sum_rec, [ ],
          [ (counter, Type (nat)); (l, Type (Ex10.List2/t, Type (Z))) ],
          Type (Z)),
          Match
            (?, Variable (?, Ex10.List2/counter),
              [
                (Constructor (O),
                  Apply
                    (?,
                      Variable
                        (?,
                          not_terminated),
                      [
                        Tuple
                          (?)
                      ]));
                (Constructor (S, counter),
                  Match
                    (9,
                      Variable
                        (9,
                          Ex10.List2/l),
                      [
                        (Constructor
                          (Ex10.List2/Nil),
                          Constant
                            (10,
                              Int(0)));
                        (Constructor
                          (Ex10.List2/Cons,
                            x,
                            xs),
                          Apply
                            (11,
                              Variable
                                (11,
                                  Z.add),
                              [
                                Variable
                                  (11,
                                    Ex10.List2/x);
                                Apply
                                  (11,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            Ex10.List2/sum_rec),
                                        [
                                          Variable
                                            (?,
                                              Ex10.List2/counter)
                                        ]),
                                    [
                                      Variable
                                        (11,
                                          Ex10.List2/xs)
                                    ])
                              ]))
                      ]))
              ]))
      ])
  
  8
  Value
    (non_rec, @.,
      [
        ((sum, [ ], [ (l, Type (Ex10.List2/t, Type (Z))) ], Type (Z)),
          Apply
            (?, Variable (?, Ex10.List2/sum_rec),
              [
                Apply
                  (?,
                    Variable
                      (?,
                        read_counter),
                    [
                      Tuple
                        (?)
                    ]);
                Variable (?, Ex10.List2/l)
              ]))
      ])
  
  13
  Value
    (rec, @.,
      [
        ((of_list_rec, [ A ], [ (counter, Type (nat)); (x, Type (list, A)) ],
          Type (Ex10.List2/t, A)),
          Match
            (?, Variable (?, Ex10.List2/counter),
              [
                (Constructor (O),
                  Apply
                    (?,
                      Variable
                        (?,
                          not_terminated),
                      [
                        Tuple
                          (?)
                      ]));
                (Constructor (S, counter),
                  Match
                    (14,
                      Variable
                        (?,
                          Ex10.List2/x),
                      [
                        (Constructor
                          ([]),
                          Constructor
                            (14,
                              Ex10.List2/Nil));
                        (Constructor
                          (cons,
                            x,
                            xs),
                          Constructor
                            (15,
                              Ex10.List2/Cons,
                              Variable
                                (15,
                                  Ex10.List2/x),
                              Apply
                                (15,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          Ex10.List2/of_list_rec),
                                      [
                                        Variable
                                          (?,
                                            Ex10.List2/counter)
                                      ]),
                                  [
                                    Variable
                                      (15,
                                        Ex10.List2/xs)
                                  ])))
                      ]))
              ]))
      ])
  
  13
  Value
    (non_rec, @.,
      [
        ((of_list, [ A ], [ (x, Type (list, A)) ], Type (Ex10.List2/t, A)),
          Apply
            (?, Variable (?, Ex10.List2/of_list_rec),
              [
                Apply
                  (?,
                    Variable
                      (?,
                        read_counter),
                    [
                      Tuple
                        (?)
                    ]);
                Variable (?, Ex10.List2/x)
              ]))
      ])
  
  17 Module Inside:
    18
    Value (non_rec, @., [ ((x, [ ], [ ], Type (Z)), Constant (18, Int(12))) ])

22
Value
  (non_rec, @.,
    [
      ((n, [ A ], [ (x, A) ], Type (Z)),
        Match
          (22, Variable (?, Ex10/x),
            [
              (Any,
                Apply
                  (22,
                    Variable
                      (22,
                        Ex10/List2.sum),
                    [
                      Apply
                        (22,
                          Variable
                            (22,
                              Ex10/List2.of_list),
                          [
                            Constructor
                              (22,
                                cons,
                                Constant
                                  (22,
                                    Int(5)),
                                Constructor
                                  (22,
                                    cons,
                                    Constant
                                      (22,
                                        Int(7)),
                                    Constructor
                                      (22,
                                        cons,
                                        Constant
                                          (22,
                                            Int(6)),
                                        Constructor
                                          (22,
                                            cons,
                                            Variable
                                              (22,
                                                Ex10/List2.Inside.x),
                                            Constructor
                                              (22,
                                                [])))))
                          ])
                    ]))
            ]))
    ])
