3 Module SizedString:
  4
  Record t:
    ([ ], [ (name, Type (string)); (size, Type (Z)) ])

9
Value
  (non_rec, @.,
    [
      ((r, [ ], [ ], Type (SizedString.t)),
        Record
          (9, None, (SizedString.name, Some Constant (9, String("gre"))),
            (SizedString.size, Some Constant (9, Int(3)))))
    ])

10
Value
  (non_rec, @.,
    [
      ((r', [ ], [ ], Type (SizedString.t)),
        Record
          (10, None, (SizedString.name, Some Constant (10, String("haha"))),
            (SizedString.size, Some Constant (10, Int(4)))))
    ])

11
Value
  (non_rec, @.,
    [
      ((r'', [ ], [ ], Type (SizedString.t)),
        Record
          (11, Some Variable (11, r),
            (SizedString.name, Some Constant (11, String("GRE"))),
            (SizedString.size, None)))
    ])

13
Value
  (non_rec, @.,
    [
      ((s, [ ], [ ], Type (Z)),
        Apply
          (13, Variable (13, Z.add),
            [
              Field (13, Variable (13, r), SizedString.size);
              Field (13, Variable (13, r'), SizedString.size)
            ]))
    ])

15
Value
  (non_rec, @.,
    [
      ((f, [ ], [ (x, Type (SizedString.t)) ], Type (bool)),
        Match
          (16, Variable (?, x),
            [
              (Record ((SizedString.size, Int(3))),
                Constructor (16, true));
              (Any, Constructor (17, false))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((b, [ ], [ ], Type (bool)),
        Apply (19, Variable (19, f), [ Variable (19, r) ]))
    ])

20
Value
  (non_rec, @.,
    [
      ((b', [ ], [ ], Type (bool)),
        Apply (20, Variable (20, f), [ Variable (20, r') ]))
    ])

21
Value
  (non_rec, @.,
    [
      ((b'', [ ], [ ], Type (bool)),
        Apply (21, Variable (21, f), [ Variable (21, r'') ]))
    ])

23 Module Point:
  24
  Record t:
    ([ ], [ (x, Type (Z)); (y, Type (Z)); (z, Type (Z)) ])
  
  29
  Value
    (non_rec, @.,
      [
        ((p, [ ], [ ], Type (Point/t)),
          Record
            (29, None, (Point/x, Some Constant (29, Int(5))),
              (Point/y, Some Constant (29, Int(-3))),
              (Point/z, Some Constant (29, Int(1)))))
      ])
  
  31
  Value
    (non_rec, @.,
      [
        ((b, [ ], [ ], Type (bool)),
          Match
            (31, Variable (31, Point/p),
              [
                (Record ((Point/x, Int(5)), (Point/z, Int(1))),
                  Constructor (32, true));
                (Any, Constructor (33, false))
              ]))
      ])
  
  35
  Value
    (non_rec, @.,
      [
        ((move_right, [ ], [ (p, Type (Point/t)) ], Type (Point/t)),
          Record
            (35, Some Variable (35, Point/p),
              (Point/x,
                Some
                  Apply
                    (35, Variable (35, Z.add),
                      [
                        Field
                          (35,
                            Variable
                              (35,
                                Point/p),
                            Point/x);
                        Constant (35, Int(1))
                      ])), (Point/y, None),
              (Point/z, None)))
      ])
