3 Module SizedString:
  4
  Record t:
    ([ ], [ (name, Type (string)); (size, Type (Z)) ])

9
Value
  (non_rec, @.,
    [
      ((r, [ ], [ ], Type (Ex11/SizedString.t)),
        Record
          (9, None,
            (Ex11/SizedString.name, Some Constant (9, String("gre"))),
            (Ex11/SizedString.size, Some Constant (9, Int(3)))))
    ])

10
Value
  (non_rec, @.,
    [
      ((r', [ ], [ ], Type (Ex11/SizedString.t)),
        Record
          (10, None,
            (Ex11/SizedString.name, Some Constant (10, String("haha"))),
            (Ex11/SizedString.size, Some Constant (10, Int(4)))))
    ])

11
Value
  (non_rec, @.,
    [
      ((r'', [ ], [ ], Type (Ex11/SizedString.t)),
        Record
          (11, Some Variable (11, Ex11/r),
            (Ex11/SizedString.name, Some Constant (11, String("GRE"))),
            (Ex11/SizedString.size, None)))
    ])

13
Value
  (non_rec, @.,
    [
      ((s, [ ], [ ], Type (Z)),
        Apply
          (13, Variable (13, Z.add),
            [
              Field (13, Variable (13, Ex11/r), Ex11/SizedString.size);
              Field (13, Variable (13, Ex11/r'), Ex11/SizedString.size)
            ]))
    ])

15
Value
  (non_rec, @.,
    [
      ((f, [ ], [ (x, Type (Ex11/SizedString.t)) ], Type (bool)),
        Match
          (16, Variable (?, Ex11/x),
            [
              (Record ((Ex11/SizedString.size, Int(3))),
                Constructor (16, true));
              (Any, Constructor (17, false))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((b, [ ], [ ], Type (bool)),
        Apply (19, Variable (19, Ex11/f), [ Variable (19, Ex11/r) ]))
    ])

20
Value
  (non_rec, @.,
    [
      ((b', [ ], [ ], Type (bool)),
        Apply (20, Variable (20, Ex11/f), [ Variable (20, Ex11/r') ]))
    ])

21
Value
  (non_rec, @.,
    [
      ((b'', [ ], [ ], Type (bool)),
        Apply (21, Variable (21, Ex11/f), [ Variable (21, Ex11/r'') ]))
    ])

23 Module Point:
  24
  Record t:
    ([ ], [ (x, Type (Z)); (y, Type (Z)); (z, Type (Z)) ])
  
  29
  Value
    (non_rec, @.,
      [
        ((p, [ ], [ ], Type (Ex11.Point/t)),
          Record
            (29, None, (Ex11.Point/x, Some Constant (29, Int(5))),
              (Ex11.Point/y, Some Constant (29, Int(-3))),
              (Ex11.Point/z, Some Constant (29, Int(1)))))
      ])
  
  31
  Value
    (non_rec, @.,
      [
        ((b, [ ], [ ], Type (bool)),
          Match
            (31, Variable (31, Ex11.Point/p),
              [
                (Record
                  ((Ex11.Point/x,
                    Int(5)),
                    (Ex11.Point/z,
                      Int(1))),
                  Constructor (32, true));
                (Any, Constructor (33, false))
              ]))
      ])
  
  35
  Value
    (non_rec, @.,
      [
        ((move_right, [ ], [ (p, Type (Ex11.Point/t)) ], Type (Ex11.Point/t)),
          Record
            (35, Some Variable (35, Ex11.Point/p),
              (Ex11.Point/x,
                Some
                  Apply
                    (35, Variable (35, Z.add),
                      [
                        Field
                          (35,
                            Variable
                              (35,
                                Ex11.Point/p),
                            Ex11.Point/x);
                        Constant (35, Int(1))
                      ])), (Ex11.Point/y, None),
              (Ex11.Point/z, None)))
      ])
