3
Inductive tree:
  ([ ],
    [ (Leaf, [ ]); (Node, [ Type (Ex12/tree); Type (Z); Type (Ex12/tree) ]) ])

7
Value
  (rec, @.,
    [
      ((find_rec, [ ],
        [ (counter, Type (nat)); (x, Type (Z)); (t, Type (Ex12/tree)) ],
        Type (bool)),
        Match
          (?, Variable (?, Ex12/counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (8,
                    Variable
                      (8,
                        Ex12/t),
                    [
                      (Constructor
                        (Ex12/Leaf),
                        Constructor
                          (9,
                            false));
                      (Constructor
                        (Ex12/Node,
                          t1,
                          x',
                          t2),
                        IfThenElse
                          (11,
                            Apply
                              (11,
                                Variable
                                  (11,
                                    OCaml/Pervasives.lt),
                                [
                                  Variable
                                    (11,
                                      Ex12/x);
                                  Variable
                                    (11,
                                      Ex12/x')
                                ]),
                            Apply
                              (12,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        Ex12/find_rec),
                                    [
                                      Variable
                                        (?,
                                          Ex12/counter)
                                    ]),
                                [
                                  Variable
                                    (12,
                                      Ex12/x);
                                  Variable
                                    (12,
                                      Ex12/t1)
                                ]),
                            IfThenElse
                              (13,
                                Apply
                                  (13,
                                    Variable
                                      (13,
                                        OCaml/Pervasives.lt),
                                    [
                                      Variable
                                        (13,
                                          Ex12/x');
                                      Variable
                                        (13,
                                          Ex12/x)
                                    ]),
                                Apply
                                  (14,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            Ex12/find_rec),
                                        [
                                          Variable
                                            (?,
                                              Ex12/counter)
                                        ]),
                                    [
                                      Variable
                                        (14,
                                          Ex12/x);
                                      Variable
                                        (14,
                                          Ex12/t2)
                                    ]),
                                Constructor
                                  (16,
                                    true))))
                    ]))
            ]))
    ])

7
Value
  (non_rec, @.,
    [
      ((find, [ ], [ (x, Type (Z)); (t, Type (Ex12/tree)) ], Type (bool)),
        Apply
          (?, Variable (?, Ex12/find_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, Ex12/x);
              Variable (?, Ex12/t)
            ]))
    ])
