3
Value
  (non_rec, @.,
    [
      ((f, [ ], [ (n, Type (Z/3)); (b, Type (bool/3)) ], Type (Z/3)),
        IfThenElse
          (4, Variable (4, b/0),
            Apply
              (5, Variable (5, Z.add/3),
                [ Variable (5, n/0); Constant (5, Int(1)) ]),
            Apply
              (7, Variable (7, Z.sub/3),
                [ Variable (7, n/0); Constant (7, Int(1)) ])))
    ])
