3
Inductive set:
  ([ ], [ (Empty, [ ]); (Node, [ Type (set); Type (Z); Type (set) ]) ])

7
Value (non_rec, @., [ ((empty, [ ], [ ], Type (set)), Constructor (7, Empty)) ])

9
Value
  (rec, @.,
    [
      ((member_rec, [ ],
        [ (counter, Type (nat)); (x, Type (Z)); (s, Type (set)) ], Type (bool)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (10, Variable (10, s),
                    [
                      (Constructor
                        (Empty),
                        Constructor
                          (11,
                            false));
                      (Constructor
                        (Node,
                          s1,
                          y,
                          s2),
                        IfThenElse
                          (13,
                            Apply
                              (13,
                                Variable
                                  (13,
                                    OCaml.Pervasives.lt),
                                [
                                  Variable
                                    (13,
                                      x);
                                  Variable
                                    (13,
                                      y)
                                ]),
                            Apply
                              (14,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        member_rec),
                                    [
                                      Variable
                                        (?,
                                          counter)
                                    ]),
                                [
                                  Variable
                                    (14,
                                      x);
                                  Variable
                                    (14,
                                      s1)
                                ]),
                            IfThenElse
                              (15,
                                Apply
                                  (15,
                                    Variable
                                      (15,
                                        OCaml.Pervasives.lt),
                                    [
                                      Variable
                                        (15,
                                          y);
                                      Variable
                                        (15,
                                          x)
                                    ]),
                                Apply
                                  (16,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            member_rec),
                                        [
                                          Variable
                                            (?,
                                              counter)
                                        ]),
                                    [
                                      Variable
                                        (16,
                                          x);
                                      Variable
                                        (16,
                                          s2)
                                    ]),
                                Constructor
                                  (18,
                                    true))))
                    ]))
            ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((member, [ ], [ (x, Type (Z)); (s, Type (set)) ], Type (bool)),
        Apply
          (?, Variable (?, member_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, x);
              Variable (?, s)
            ]))
    ])

20
Value
  (rec, @.,
    [
      ((insert_rec, [ ],
        [ (counter, Type (nat)); (x, Type (Z)); (s, Type (set)) ], Type (set)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (21, Variable (21, s),
                    [
                      (Constructor
                        (Empty),
                        Constructor
                          (22,
                            Node,
                            Constructor
                              (22,
                                Empty),
                            Variable
                              (22,
                                x),
                            Constructor
                              (22,
                                Empty)));
                      (Constructor
                        (Node,
                          s1,
                          y,
                          s2),
                        IfThenElse
                          (24,
                            Apply
                              (24,
                                Variable
                                  (24,
                                    OCaml.Pervasives.lt),
                                [
                                  Variable
                                    (24,
                                      x);
                                  Variable
                                    (24,
                                      y)
                                ]),
                            Constructor
                              (25,
                                Node,
                                Apply
                                  (25,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            insert_rec),
                                        [
                                          Variable
                                            (?,
                                              counter)
                                        ]),
                                    [
                                      Variable
                                        (25,
                                          x);
                                      Variable
                                        (25,
                                          s1)
                                    ]),
                                Variable
                                  (25,
                                    y),
                                Variable
                                  (25,
                                    s2)),
                            IfThenElse
                              (26,
                                Apply
                                  (26,
                                    Variable
                                      (26,
                                        OCaml.Pervasives.lt),
                                    [
                                      Variable
                                        (26,
                                          y);
                                      Variable
                                        (26,
                                          x)
                                    ]),
                                Constructor
                                  (27,
                                    Node,
                                    Variable
                                      (27,
                                        s1),
                                    Variable
                                      (27,
                                        y),
                                    Apply
                                      (27,
                                        Apply
                                          (?,
                                            Variable
                                              (?,
                                                insert_rec),
                                            [
                                              Variable
                                                (?,
                                                  counter)
                                            ]),
                                        [
                                          Variable
                                            (27,
                                              x);
                                          Variable
                                            (27,
                                              s2)
                                        ])),
                                Variable
                                  (28,
                                    s))))
                    ]))
            ]))
    ])

20
Value
  (non_rec, @.,
    [
      ((insert, [ ], [ (x, Type (Z)); (s, Type (set)) ], Type (set)),
        Apply
          (?, Variable (?, insert_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, x);
              Variable (?, s)
            ]))
    ])
