3
Inductive set:
  ([ ], [ (Empty, [ ]); (Node, [ Type (Ex15/set); Type (Z); Type (Ex15/set) ]) ])

7
Value
  (non_rec, @.,
    [ ((empty, [ ], [ ], Type (Ex15/set)), Constructor (7, Ex15/Empty)) ])

9
Value
  (rec, @.,
    [
      ((member_rec, [ ],
        [ (counter, Type (nat)); (x, Type (Z)); (s, Type (Ex15/set)) ],
        Type (bool)),
        Match
          (?, Variable (?, Ex15/counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (10,
                    Variable
                      (10,
                        Ex15/s),
                    [
                      (Constructor
                        (Ex15/Empty),
                        Constructor
                          (11,
                            false));
                      (Constructor
                        (Ex15/Node,
                          s1,
                          y,
                          s2),
                        IfThenElse
                          (13,
                            Apply
                              (13,
                                Variable
                                  (13,
                                    OCaml/Pervasives.lt),
                                [
                                  Variable
                                    (13,
                                      Ex15/x);
                                  Variable
                                    (13,
                                      Ex15/y)
                                ]),
                            Apply
                              (14,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        Ex15/member_rec),
                                    [
                                      Variable
                                        (?,
                                          Ex15/counter)
                                    ]),
                                [
                                  Variable
                                    (14,
                                      Ex15/x);
                                  Variable
                                    (14,
                                      Ex15/s1)
                                ]),
                            IfThenElse
                              (15,
                                Apply
                                  (15,
                                    Variable
                                      (15,
                                        OCaml/Pervasives.lt),
                                    [
                                      Variable
                                        (15,
                                          Ex15/y);
                                      Variable
                                        (15,
                                          Ex15/x)
                                    ]),
                                Apply
                                  (16,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            Ex15/member_rec),
                                        [
                                          Variable
                                            (?,
                                              Ex15/counter)
                                        ]),
                                    [
                                      Variable
                                        (16,
                                          Ex15/x);
                                      Variable
                                        (16,
                                          Ex15/s2)
                                    ]),
                                Constructor
                                  (18,
                                    true))))
                    ]))
            ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((member, [ ], [ (x, Type (Z)); (s, Type (Ex15/set)) ], Type (bool)),
        Apply
          (?, Variable (?, Ex15/member_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, Ex15/x);
              Variable (?, Ex15/s)
            ]))
    ])

20
Value
  (rec, @.,
    [
      ((insert_rec, [ ],
        [ (counter, Type (nat)); (x, Type (Z)); (s, Type (Ex15/set)) ],
        Type (Ex15/set)),
        Match
          (?, Variable (?, Ex15/counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (21,
                    Variable
                      (21,
                        Ex15/s),
                    [
                      (Constructor
                        (Ex15/Empty),
                        Constructor
                          (22,
                            Ex15/Node,
                            Constructor
                              (22,
                                Ex15/Empty),
                            Variable
                              (22,
                                Ex15/x),
                            Constructor
                              (22,
                                Ex15/Empty)));
                      (Constructor
                        (Ex15/Node,
                          s1,
                          y,
                          s2),
                        IfThenElse
                          (24,
                            Apply
                              (24,
                                Variable
                                  (24,
                                    OCaml/Pervasives.lt),
                                [
                                  Variable
                                    (24,
                                      Ex15/x);
                                  Variable
                                    (24,
                                      Ex15/y)
                                ]),
                            Constructor
                              (25,
                                Ex15/Node,
                                Apply
                                  (25,
                                    Apply
                                      (?,
                                        Variable
                                          (?,
                                            Ex15/insert_rec),
                                        [
                                          Variable
                                            (?,
                                              Ex15/counter)
                                        ]),
                                    [
                                      Variable
                                        (25,
                                          Ex15/x);
                                      Variable
                                        (25,
                                          Ex15/s1)
                                    ]),
                                Variable
                                  (25,
                                    Ex15/y),
                                Variable
                                  (25,
                                    Ex15/s2)),
                            IfThenElse
                              (26,
                                Apply
                                  (26,
                                    Variable
                                      (26,
                                        OCaml/Pervasives.lt),
                                    [
                                      Variable
                                        (26,
                                          Ex15/y);
                                      Variable
                                        (26,
                                          Ex15/x)
                                    ]),
                                Constructor
                                  (27,
                                    Ex15/Node,
                                    Variable
                                      (27,
                                        Ex15/s1),
                                    Variable
                                      (27,
                                        Ex15/y),
                                    Apply
                                      (27,
                                        Apply
                                          (?,
                                            Variable
                                              (?,
                                                Ex15/insert_rec),
                                            [
                                              Variable
                                                (?,
                                                  Ex15/counter)
                                            ]),
                                        [
                                          Variable
                                            (27,
                                              Ex15/x);
                                          Variable
                                            (27,
                                              Ex15/s2)
                                        ])),
                                Variable
                                  (28,
                                    Ex15/s))))
                    ]))
            ]))
    ])

20
Value
  (non_rec, @.,
    [
      ((insert, [ ], [ (x, Type (Z)); (s, Type (Ex15/set)) ], Type (Ex15/set)),
        Apply
          (?, Variable (?, Ex15/insert_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, Ex15/x);
              Variable (?, Ex15/s)
            ]))
    ])
