3 Exception (Outside, outside, ())

5
Value
  (non_rec, @.,
    [
      ((f, [ A; B ], [ (x, A) ], B),
        Apply
          (5, Variable (5, OCaml.Pervasives.raise),
            [ Constructor (5, Outside, Tuple (?)) ]))
    ])

7 Module G:
  8 Exception (Inside, inside, (Type (Z) * Type (string)))
  
  10
  Value
    (non_rec, @.,
      [
        ((g, [ A ], [ (b, Type (bool)) ], A),
          IfThenElse
            (11, Variable (11, G/b),
              Apply
                (12, Variable (12, OCaml.Pervasives.raise),
                  [
                    Constructor
                      (12,
                        G/Inside,
                        Tuple
                          (?,
                            Constant
                              (12,
                                Int(12)),
                            Constant
                              (12,
                                String("no"))))
                  ]),
              Apply
                (14, Variable (14, OCaml.Pervasives.raise),
                  [ Constructor (14, Outside, Tuple (?)) ])))
      ])

17
Value
  (rec, @.,
    [
      ((h_rec, [ A; B ], [ (counter, Type (nat)); (l, Type (list, A)) ], B),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (18, Variable (18, l),
                    [
                      (Constructor
                        ([]),
                        Sequence
                          (19,
                            Apply
                              (19,
                                Variable
                                  (19,
                                    OCaml.Pervasives.print_string),
                                [
                                  Constant
                                    (19,
                                      String("no tail"))
                                ]),
                            Apply
                              (19,
                                Variable
                                  (19,
                                    G.g),
                                [
                                  Constructor
                                    (19,
                                      false)
                                ])));
                      (Constructor
                        (cons,
                          x,
                          Constructor
                            ([])),
                        Apply
                          (20,
                            Variable
                              (20,
                                OCaml.Pervasives.raise),
                            [
                              Constructor
                                (20,
                                  G.Inside,
                                  Tuple
                                    (?,
                                      Constant
                                        (20,
                                          Int(0)),
                                      Constant
                                        (20,
                                          String("gg"))))
                            ]));
                      (Constructor
                        (cons,
                          Any,
                          xs),
                        Apply
                          (21,
                            Apply
                              (?,
                                Variable
                                  (?,
                                    h_rec),
                                [
                                  Variable
                                    (?,
                                      counter)
                                ]),
                            [
                              Variable
                                (21,
                                  xs)
                            ]))
                    ]))
            ]))
    ])

17
Value
  (non_rec, @.,
    [
      ((h, [ A; B ], [ (l, Type (list, A)) ], B),
        Apply
          (?, Variable (?, h_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, l)
            ]))
    ])
