1 Reference (r, r_state, Type (Z), Constant (1, Int(12)))

3
Value
  (non_rec, @.,
    [
      ((plus_one, [ A ], [ (x, A) ], Type (Z)),
        Match
          (3, Variable (?, x),
            [
              (Any,
                Apply
                  (4,
                    Variable
                      (4,
                        Z.add),
                    [
                      Apply
                        (4,
                          Variable
                            (4,
                              OCaml.Effect.State.read),
                          [
                            Variable
                              (4,
                                r)
                          ]);
                      Constant
                        (4,
                          Int(1))
                    ]))
            ]))
    ])

6 Reference (s, s_state, Type (string), Constant (6, String("Hi")))

8
Value
  (non_rec, @.,
    [
      ((fail, [ A; B ], [ (x, A) ], B),
        Match
          (8, Variable (?, x),
            [
              (Any,
                Apply
                  (8,
                    Variable
                      (8,
                        OCaml.Pervasives.failwith),
                    [
                      Apply
                        (8,
                          Variable
                            (8,
                              OCaml.Effect.State.read),
                          [
                            Variable
                              (8,
                                s)
                          ])
                    ]))
            ]))
    ])

10
Value
  (non_rec, @.,
    [
      ((reset, [ A ], [ (x, A) ], Type (unit)),
        Match
          (10, Variable (?, x),
            [
              (Any,
                Apply
                  (11,
                    Variable
                      (11,
                        OCaml.Effect.State.write),
                    [
                      Variable
                        (11,
                          r);
                      Constant
                        (11,
                          Int(0))
                    ]))
            ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((incr, [ A ], [ (x, A) ], Type (unit)),
        Match
          (13, Variable (?, x),
            [
              (Any,
                Apply
                  (14,
                    Variable
                      (14,
                        OCaml.Effect.State.write),
                    [
                      Variable
                        (14,
                          r);
                      Apply
                        (14,
                          Variable
                            (14,
                              Z.add),
                          [
                            Apply
                              (14,
                                Variable
                                  (14,
                                    OCaml.Effect.State.read),
                                [
                                  Variable
                                    (14,
                                      r)
                                ]);
                            Constant
                              (14,
                                Int(1))
                          ])
                    ]))
            ]))
    ])
