1 Reference (r, r_state, Type (Z/3), Constant (1, Int(12)))

3
Value
  (non_rec, @.,
    [
      ((plus_one, [ A ], [ (x, A) ], Type (Z/3)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (4,
                    Variable
                      (4,
                        Z.add/3),
                    [
                      Apply
                        (4,
                          Variable
                            (4,
                              OCaml.Effect.State.read/3),
                          [
                            Variable
                              (4,
                                r/0)
                          ]);
                      Constant
                        (4,
                          Int(1))
                    ]))
            ]))
    ])

6 Reference (s, s_state, Type (string/3), Constant (6, String("Hi")))

8
Value
  (non_rec, @.,
    [
      ((fail, [ A; B ], [ (x, A) ], B),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (8,
                    Variable
                      (8,
                        OCaml.Pervasives.failwith/3),
                    [
                      Apply
                        (8,
                          Variable
                            (8,
                              OCaml.Effect.State.read/3),
                          [
                            Variable
                              (8,
                                s/0)
                          ])
                    ]))
            ]))
    ])

10
Value
  (non_rec, @.,
    [
      ((reset, [ A ], [ (x, A) ], Type (unit/3)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (11,
                    Variable
                      (11,
                        OCaml.Effect.State.write/3),
                    [
                      Variable
                        (11,
                          r/0);
                      Constant
                        (11,
                          Int(0))
                    ]))
            ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((incr, [ A ], [ (x, A) ], Type (unit/3)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (14,
                    Variable
                      (14,
                        OCaml.Effect.State.write/3),
                    [
                      Variable
                        (14,
                          r/0);
                      Apply
                        (14,
                          Variable
                            (14,
                              Z.add/3),
                          [
                            Apply
                              (14,
                                Variable
                                  (14,
                                    OCaml.Effect.State.read/3),
                                [
                                  Variable
                                    (14,
                                      r/0)
                                ]);
                            Constant
                              (14,
                                Int(1))
                          ])
                    ]))
            ]))
    ])
