3 Exception (Error, error, ())

5
Value
  (non_rec, @.,
    [
      ((x1, [ ], [ ], Type (Z)),
        Match
          (6,
            Run
              (?, Type (OCaml/exception, Type (Ex19/error)), [ ],
                Apply
                  (6, Variable (6, OCaml/Pervasives.raise),
                    [ Constructor (6, Ex19/Error, Tuple (?)) ])),
            [
              (Constructor (inl, x), Variable (?, Ex19/x));
              (Constructor (inr, Constructor (Ex19/Error, Tuple ())),
                Constant (7, Int(12)))
            ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((x2, [ A; B ], [ (x, A) ], B),
        Match
          (9, Variable (?, Ex19/x),
            [
              (Any,
                Match
                  (10,
                    Run
                      (?,
                        Type
                          (OCaml/exception,
                            Type
                              (Ex19/error)),
                        [
                        ],
                        Apply
                          (10,
                            Variable
                              (10,
                                OCaml/Pervasives.raise),
                            [
                              Constructor
                                (10,
                                  Ex19/Error,
                                  Tuple
                                    (?))
                            ])),
                    [
                      (Constructor
                        (inl,
                          x),
                        Variable
                          (?,
                            Ex19/x));
                      (Constructor
                        (inr,
                          Constructor
                            (Ex19/Error,
                              Tuple
                                ())),
                        Apply
                          (11,
                            Variable
                              (11,
                                OCaml/Pervasives.failwith),
                            [
                              Constant
                                (11,
                                  String("arg"))
                            ]))
                    ]))
            ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((x3, [ ], [ (b, Type (bool)) ], Type (Z)),
        Match
          (14,
            Run
              (?, Type (OCaml/exception, Type (Ex19/error)), [ ],
                IfThenElse
                  (14, Variable (14, Ex19/b),
                    Apply
                      (14,
                        Variable
                          (14, OCaml/Pervasives.failwith),
                        [ Constant (14, String("arg")) ]),
                    Apply
                      (14,
                        Variable (14, OCaml/Pervasives.raise),
                        [
                          Constructor
                            (14,
                              Ex19/Error,
                              Tuple
                                (?))
                        ]))),
            [
              (Constructor (inl, x), Variable (?, Ex19/x));
              (Constructor (inr, Constructor (Ex19/Error, Tuple ())),
                Constant (15, Int(12)))
            ]))
    ])

17
Value
  (non_rec, @.,
    [
      ((x4, [ ], [ ], Type (Z)),
        Match
          (18,
            Run
              (?, Type (OCaml/exception, _), [ ],
                Apply
                  (18, Variable (18, OCaml/Pervasives.failwith),
                    [ Constant (18, String("arg")) ])),
            [
              (Constructor (inl, x), Variable (?, Ex19/x));
              (Constructor (inr, Any), Constant (19, Int(12)))
            ]))
    ])
