3
Value
  (non_rec, @.,
    [
      ((f, [ A; B; C ], [ (x, A) ], (B -> C)),
        Sequence
          (4,
            Apply
              (4, Variable (4, OCaml/Pervasives.print_string),
                [ Constant (4, String("Hi")) ]),
            Function
              (5, y,
                Apply
                  (5, Variable (5, OCaml/Pervasives.failwith),
                    [ Constant (5, String("Bye")) ]))))
    ])

7
Value
  (non_rec, @.,
    [
      ((r, [ A; B ], [ (x, A) ], B),
        Match
          (7, Variable (?, Ex21/x),
            [
              (Any,
                Apply
                  (7,
                    Variable
                      (7,
                        Ex21/f),
                    [
                      Constant
                        (7,
                          Int(1));
                      Constant
                        (7,
                          Int(2))
                    ]))
            ]))
    ])
