3
Value
  (rec, @coq_rec,
    [
      ((odd_length, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Match
          (4, Variable (4, l),
            [
              (Constructor ([]), Constructor (5, false));
              (Constructor (cons, Any, l),
                Apply
                  (6,
                    Variable
                      (6,
                        negb),
                    [
                      Apply
                        (6,
                          Variable
                            (6,
                              even_length),
                          [
                            Variable
                              (6,
                                l)
                          ])
                    ]))
            ]));
      ((even_length, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Match
          (10, Variable (10, l),
            [
              (Constructor ([]), Constructor (11, true));
              (Constructor (cons, Any, l),
                Apply
                  (12,
                    Variable
                      (12,
                        negb),
                    [
                      Apply
                        (12,
                          Variable
                            (12,
                              odd_length),
                          [
                            Variable
                              (12,
                                l)
                          ])
                    ]))
            ]))
    ])

14
Value
  (rec, @coq_rec,
    [
      ((odd_length_with_print, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Match
          (15, Variable (15, l),
            [
              (Constructor ([]),
                Sequence
                  (16,
                    Apply
                      (16,
                        Variable
                          (16,
                            OCaml.Pervasives.print_endline),
                        [
                          Constant
                            (16,
                              String("false"))
                        ]),
                    Constructor
                      (16,
                        false)));
              (Constructor (cons, Any, l),
                Apply
                  (17,
                    Variable
                      (17,
                        negb),
                    [
                      Apply
                        (17,
                          Variable
                            (17,
                              even_length_with_print),
                          [
                            Variable
                              (17,
                                l)
                          ])
                    ]))
            ]));
      ((even_length_with_print, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Match
          (21, Variable (21, l),
            [
              (Constructor ([]), Constructor (22, true));
              (Constructor (cons, Any, l),
                Apply
                  (23,
                    Variable
                      (23,
                        negb),
                    [
                      Apply
                        (23,
                          Variable
                            (23,
                              odd_length_with_print),
                          [
                            Variable
                              (23,
                                l)
                          ])
                    ]))
            ]))
    ])

25
Value
  (rec, @.,
    [
      ((odd_length_free_rec, [ A ],
        [ (counter, Type (nat)); (l, Type (list, A)) ], Type (bool)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (26, Variable (26, l),
                    [
                      (Constructor
                        ([]),
                        Constructor
                          (27,
                            false));
                      (Constructor
                        (cons,
                          Any,
                          l),
                        Apply
                          (28,
                            Variable
                              (28,
                                negb),
                            [
                              Apply
                                (28,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          even_length_free_rec),
                                      [
                                        Variable
                                          (?,
                                            counter)
                                      ]),
                                  [
                                    Variable
                                      (28,
                                        l)
                                  ])
                            ]))
                    ]))
            ]));
      ((even_length_free_rec, [ A ],
        [ (counter, Type (nat)); (l, Type (list, A)) ], Type (bool)),
        Match
          (?, Variable (?, counter),
            [
              (Constructor (O),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S, counter),
                Match
                  (31, Variable (31, l),
                    [
                      (Constructor
                        ([]),
                        Constructor
                          (32,
                            true));
                      (Constructor
                        (cons,
                          Any,
                          l),
                        Apply
                          (33,
                            Variable
                              (33,
                                negb),
                            [
                              Apply
                                (33,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          odd_length_free_rec),
                                      [
                                        Variable
                                          (?,
                                            counter)
                                      ]),
                                  [
                                    Variable
                                      (33,
                                        l)
                                  ])
                            ]))
                    ]))
            ]))
    ])

25
Value
  (non_rec, @.,
    [
      ((odd_length_free, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Apply
          (?, Variable (?, odd_length_free_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, l)
            ]))
    ])

25
Value
  (non_rec, @.,
    [
      ((even_length_free, [ A ], [ (l, Type (list, A)) ], Type (bool)),
        Apply
          (?, Variable (?, even_length_free_rec),
            [
              Apply (?, Variable (?, read_counter), [ Tuple (?) ]);
              Variable (?, l)
            ]))
    ])
