3
Value
  (rec, @coq_rec,
    [
      ((odd_length, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (4, Variable (4, l/0),
            [
              (Constructor ([]/3), Constructor (5, false/3));
              (Constructor (cons/3, Any, l),
                Apply
                  (6,
                    Variable
                      (6,
                        negb/3),
                    [
                      Apply
                        (6,
                          Variable
                            (6,
                              even_length/0),
                          [
                            Variable
                              (6,
                                l/0)
                          ])
                    ]))
            ]));
      ((even_length, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (10, Variable (10, l/0),
            [
              (Constructor ([]/3), Constructor (11, true/3));
              (Constructor (cons/3, Any, l),
                Apply
                  (12,
                    Variable
                      (12,
                        negb/3),
                    [
                      Apply
                        (12,
                          Variable
                            (12,
                              odd_length/0),
                          [
                            Variable
                              (12,
                                l/0)
                          ])
                    ]))
            ]))
    ])

14
Value
  (rec, @coq_rec,
    [
      ((odd_length_with_print, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (15, Variable (15, l/0),
            [
              (Constructor ([]/3),
                Sequence
                  (16,
                    Apply
                      (16,
                        Variable
                          (16,
                            OCaml.Pervasives.print_endline/3),
                        [
                          Constant
                            (16,
                              String("false"))
                        ]),
                    Constructor
                      (16,
                        false/3)));
              (Constructor (cons/3, Any, l),
                Apply
                  (17,
                    Variable
                      (17,
                        negb/3),
                    [
                      Apply
                        (17,
                          Variable
                            (17,
                              even_length_with_print/0),
                          [
                            Variable
                              (17,
                                l/0)
                          ])
                    ]))
            ]));
      ((even_length_with_print, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (21, Variable (21, l/0),
            [
              (Constructor ([]/3), Constructor (22, true/3));
              (Constructor (cons/3, Any, l),
                Apply
                  (23,
                    Variable
                      (23,
                        negb/3),
                    [
                      Apply
                        (23,
                          Variable
                            (23,
                              odd_length_with_print/0),
                          [
                            Variable
                              (23,
                                l/0)
                          ])
                    ]))
            ]))
    ])

25
Value
  (rec, @.,
    [
      ((odd_length_free_rec, [ A ],
        [ (counter, Type (nat/3)); (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (?, Variable (?, counter/0),
            [
              (Constructor (O/3),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated/3),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S/3, counter),
                Match
                  (26,
                    Variable
                      (26,
                        l/0),
                    [
                      (Constructor
                        ([]/3),
                        Constructor
                          (27,
                            false/3));
                      (Constructor
                        (cons/3,
                          Any,
                          l),
                        Apply
                          (28,
                            Variable
                              (28,
                                negb/3),
                            [
                              Apply
                                (28,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          even_length_free_rec/0),
                                      [
                                        Variable
                                          (?,
                                            counter/0)
                                      ]),
                                  [
                                    Variable
                                      (28,
                                        l/0)
                                  ])
                            ]))
                    ]))
            ]));
      ((even_length_free_rec, [ A ],
        [ (counter, Type (nat/3)); (l, Type (list/3, A)) ], Type (bool/3)),
        Match
          (?, Variable (?, counter/0),
            [
              (Constructor (O/3),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated/3),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S/3, counter),
                Match
                  (31,
                    Variable
                      (31,
                        l/0),
                    [
                      (Constructor
                        ([]/3),
                        Constructor
                          (32,
                            true/3));
                      (Constructor
                        (cons/3,
                          Any,
                          l),
                        Apply
                          (33,
                            Variable
                              (33,
                                negb/3),
                            [
                              Apply
                                (33,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          odd_length_free_rec/0),
                                      [
                                        Variable
                                          (?,
                                            counter/0)
                                      ]),
                                  [
                                    Variable
                                      (33,
                                        l/0)
                                  ])
                            ]))
                    ]))
            ]))
    ])

25
Value
  (non_rec, @.,
    [
      ((odd_length_free, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Apply
          (?, Variable (?, odd_length_free_rec/0),
            [
              Apply (?, Variable (?, read_counter/3), [ Tuple (?) ]);
              Variable (?, l/0)
            ]))
    ])

25
Value
  (non_rec, @.,
    [
      ((even_length_free, [ A ], [ (l, Type (list/3, A)) ], Type (bool/3)),
        Apply
          (?, Variable (?, even_length_free_rec/0),
            [
              Apply (?, Variable (?, read_counter/3), [ Tuple (?) ]);
              Variable (?, l/0)
            ]))
    ])
