3 Exception (Fail, fail, (Type (string)))

5
Value
  (non_rec, @.,
    [
      ((div, [ ], [ (n, Type (Z)) ], Type (Z)),
        IfThenElse
          (6,
            Apply
              (6, Variable (6, equiv_decb),
                [ Variable (6, Ex35/n); Constant (6, Int(0)) ]),
            Apply
              (7, Variable (7, OCaml/Pervasives.raise),
                [
                  Constructor
                    (7, Ex35/Fail,
                      Tuple
                        (?,
                          Constant
                            (7,
                              String("n is null"))))
                ]),
            Apply
              (9, Variable (9, Z.div),
                [ Constant (9, Int(256)); Variable (9, Ex35/n) ])))
    ])
