3 Exception (Fail, raise_Fail, (Type (string/3)))

5
Value
  (non_rec, @.,
    [
      ((div, [ ], [ (n, Type (Z/3)) ], Type (Z/3)),
        IfThenElse
          (6,
            Apply
              (6, Variable (6, equiv_decb/3),
                [ Variable (6, n/0); Constant (6, Int(0)) ]),
            Apply
              (7, Variable (7, raise_Fail/0),
                [ Tuple (?, Constant (7, String("n is null"))) ]),
            Apply
              (9, Variable (9, Z.div/3),
                [ Constant (9, Int(256)); Variable (9, n/0) ])))
    ])
