5 Open Dependency

7
Value
  (non_rec, @.,
    [ ((a, [ ], [ ], Some Type (string/1)), Variable (7, Dependency.a/-1)) ])

8
Value
  (non_rec, @.,
    [
      ((b, [ ], [ ], Some (Type (unit/1) -> Type (unit/1))),
        Variable (8, Dependency.b/-1))
    ])

9
Value
  (non_rec, @.,
    [
      ((c, [ ], [ ], Some (Type (unit/1) -> Type (string/1))),
        Variable (9, Dependency.C.c/-1))
    ])
