3 Primitive (op_eq_eq, [ ], (Type (bool) -> (Type (bool) -> Type (bool))))

5
Value
  (non_rec, @.,
    [
      ((all_eqb, [ ], [ (x, Type (bool)); (y, Type (bool)); (z, Type (bool)) ],
        Type (bool)),
        Apply
          (5, Variable (5, andb),
            [
              Apply
                (5, Variable (5, Ex36/op_eq_eq),
                  [
                    Variable
                      (5,
                        Ex36/x);
                    Variable
                      (5,
                        Ex36/y)
                  ]);
              Apply
                (5, Variable (5, Ex36/op_eq_eq),
                  [
                    Variable
                      (5,
                        Ex36/y);
                    Variable
                      (5,
                        Ex36/z)
                  ])
            ]))
    ])

8 Primitive (op_eq, [ A ], (A -> (A -> Type (bool))))

10
Value
  (non_rec, @.,
    [
      ((all_equal, [ A ], [ (x, A); (y, A); (z, A) ], Type (bool)),
        Apply
          (10, Variable (10, andb),
            [
              Apply
                (10, Variable (10, Ex36/op_eq),
                  [
                    Variable
                      (10,
                        Ex36/x);
                    Variable
                      (10,
                        Ex36/y)
                  ]);
              Apply
                (10, Variable (10, Ex36/op_eq),
                  [
                    Variable
                      (10,
                        Ex36/y);
                    Variable
                      (10,
                        Ex36/z)
                  ])
            ]))
    ])
