3 Primitive (op_eq_eq, [ ], (Type (bool/1) -> (Type (bool/1) -> Type (bool/1))))

5
Value
  (non_rec, @.,
    [
      ((all_eqb, [ ],
        [ (x, Type (bool/1)); (y, Type (bool/1)); (z, Type (bool/1)) ],
        Type (bool/1)),
        Apply
          (5, Variable (5, andb/1),
            [
              Apply
                (5, Variable (5, op_eq_eq/0),
                  [
                    Variable
                      (5,
                        x/0);
                    Variable
                      (5,
                        y/0)
                  ]);
              Apply
                (5, Variable (5, op_eq_eq/0),
                  [
                    Variable
                      (5,
                        y/0);
                    Variable
                      (5,
                        z/0)
                  ])
            ]))
    ])

8 Primitive (op_eq, [ a ], (a -> (a -> Type (bool/1))))

10
Value
  (non_rec, @.,
    [
      ((all_equal, [ A ], [ (x, A); (y, A); (z, A) ], Type (bool/1)),
        Apply
          (10, Variable (10, andb/1),
            [
              Apply
                (10, Variable (10, op_eq/0),
                  [
                    Variable
                      (10,
                        x/0);
                    Variable
                      (10,
                        y/0)
                  ]);
              Apply
                (10, Variable (10, op_eq/0),
                  [
                    Variable
                      (10,
                        y/0);
                    Variable
                      (10,
                        z/0)
                  ])
            ]))
    ])
