Require [ OCaml.List ]

3
Value
  (non_rec, @.,
    [
      ((get_local_ref, [ ], [ (tt, Type (unit/1)) ], Type (Z/1)),
        LetVar 4 x =
          Apply
            (4, Variable (4, OCaml.Pervasives.ref/1),
              [ Constant (4, Int(12)) ]) in
        Apply
          (5, Variable (5, OCaml.Effect.State.read/1), [ Variable (5, x/0) ]))
    ])

7
Value
  (non_rec, @.,
    [
      ((set_local_ref, [ ], [ (tt, Type (unit/1)) ], Type (Z/1)),
        LetVar 8 x =
          Apply
            (8, Variable (8, OCaml.Pervasives.ref/1),
              [ Constant (8, Int(12)) ]) in
        Sequence
          (9,
            Apply
              (9, Variable (9, OCaml.Effect.State.write/1),
                [ Variable (9, x/0); Constant (9, Int(15)) ]),
            Apply
              (10, Variable (10, OCaml.Effect.State.read/1),
                [ Variable (10, x/0) ])))
    ])

12
Value
  (non_rec, @.,
    [
      ((add_multiple_by_refs, [ ],
        [ (a, Type (Z/1)); (b, Type (Z/1)); (c, Type (Z/1)); (d, Type (Z/1)) ],
        Type (Z/1)),
        LetVar 13 x =
          Apply
            (13, Variable (13, OCaml.Pervasives.ref/1),
              [ Variable (13, a/0) ]) in
        Sequence
          (14,
            Apply
              (14, Variable (14, OCaml.Effect.State.write/1),
                [
                  Variable (14, x/0);
                  Apply
                    (14,
                      Variable
                        (14,
                          Z.add/1),
                      [
                        Apply
                          (14,
                            Variable
                              (14,
                                OCaml.Effect.State.read/1),
                            [
                              Variable
                                (14,
                                  x/0)
                            ]);
                        Variable
                          (14,
                            b/0)
                      ])
                ]),
            LetVar 15 y =
              Apply
                (15, Variable (15, OCaml.Pervasives.ref/1),
                  [ Variable (15, c/0) ]) in
            Sequence
              (16,
                Apply
                  (16, Variable (16, OCaml.Effect.State.write/1),
                    [
                      Variable (16, y/0);
                      Apply
                        (16,
                          Variable
                            (16,
                              Z.add/1),
                          [
                            Apply
                              (16,
                                Variable
                                  (16,
                                    OCaml.Effect.State.read/1),
                                [
                                  Variable
                                    (16,
                                      y/0)
                                ]);
                            Variable
                              (16,
                                d/0)
                          ])
                    ]),
                LetVar 17 z =
                  Apply
                    (17, Variable (17, OCaml.Pervasives.ref/1),
                      [
                        Apply
                          (17,
                            Variable
                              (17,
                                Z.add/1),
                            [
                              Apply
                                (17,
                                  Variable
                                    (17,
                                      OCaml.Effect.State.read/1),
                                  [
                                    Variable
                                      (17,
                                        x/0)
                                  ]);
                              Apply
                                (17,
                                  Variable
                                    (17,
                                      OCaml.Effect.State.read/1),
                                  [
                                    Variable
                                      (17,
                                        y/0)
                                  ])
                            ])
                      ]) in
                Apply
                  (18, Variable (18, OCaml.Effect.State.read/1),
                    [ Variable (18, z/0) ]))))
    ])

20
Value
  (non_rec, @.,
    [
      ((set_ref, [ ], [ (x, Type (OCaml.Effect.State.t/1, Type (Z/1))) ],
        Type (unit/1)),
        Apply
          (21, Variable (21, OCaml.Effect.State.write/1),
            [ Variable (21, x/0); Constant (21, Int(15)) ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((get_ref, [ ], [ (x, Type (OCaml.Effect.State.t/1, Type (Z/1))) ],
        Type (Z/1)),
        Apply
          (24, Variable (24, OCaml.Effect.State.read/1),
            [ Variable (24, x/0) ]))
    ])

26
Value
  (non_rec, @.,
    [
      ((update_ref, [ ], [ (x, Type (OCaml.Effect.State.t/1, Type (Z/1))) ],
        Type (unit/1)),
        Apply
          (27, Variable (27, OCaml.Effect.State.write/1),
            [
              Variable (27, x/0);
              Apply
                (27, Variable (27, Z.add/1),
                  [
                    Apply
                      (27,
                        Variable
                          (27,
                            OCaml.Effect.State.read/1),
                        [
                          Variable
                            (27,
                              x/0)
                        ]);
                    Constant
                      (27,
                        Int(5))
                  ])
            ]))
    ])

29
Value
  (non_rec, @.,
    [
      ((new_ref, [ ], [ (x, Type (unit/1)) ],
        Type (OCaml.Effect.State.t/1, Type (Z/1))),
        Apply
          (30, Variable (30, OCaml.Pervasives.ref/1),
            [ Constant (30, Int(15)) ]))
    ])

32 Reference (r, r_state, Type (Z/1), Constant (32, Int(18)))

34
Value
  (non_rec, @.,
    [
      ((set_r, [ ], [ (x, Type (unit/1)) ], Type (unit/1)),
        Apply (34, Variable (34, set_ref/0), [ Variable (34, r/0) ]))
    ])

36
Value
  (non_rec, @.,
    [
      ((get_r, [ ], [ (x, Type (unit/1)) ], Type (Z/1)),
        Apply (36, Variable (36, get_ref/0), [ Variable (36, r/0) ]))
    ])

38
Value
  (non_rec, @.,
    [
      ((r_add_15, [ ], [ (x, Type (unit/1)) ], Type (Z/1)),
        LetVar 39 i =
          Apply (39, Variable (39, get_r/0), [ Constructor (39, tt/1) ]) in
        Sequence
          (40,
            Apply (40, Variable (40, set_r/0), [ Constructor (40, tt/1) ]),
            LetVar 41 j =
              Apply
                (41, Variable (41, get_r/0),
                  [ Constructor (41, tt/1) ]) in
            Sequence
              (42,
                Apply
                  (42, Variable (42, OCaml.Effect.State.write/1),
                    [
                      Variable (42, r/0);
                      Apply
                        (42,
                          Variable
                            (42,
                              Z.add/1),
                          [
                            Variable
                              (42,
                                i/0);
                            Variable
                              (42,
                                j/0)
                          ])
                    ]),
                Apply
                  (43, Variable (43, OCaml.Effect.State.read/1),
                    [ Variable (43, r/0) ]))))
    ])

45
Value
  (non_rec, @.,
    [
      ((mixed_type, [ ], [ (x, Type (unit/1)) ],
        (Type (bool/1) * Type (string/1) * Type (Z/1))),
        LetVar 46 b =
          Apply
            (46, Variable (46, OCaml.Pervasives.ref/1),
              [ Constructor (46, true/1) ]) in
        LetVar 47 str =
          Apply
            (47, Variable (47, OCaml.Pervasives.ref/1),
              [ Constant (47, String("")) ]) in
        LetFun 48
          (non_rec, @.,
            [
              ((update, [ ], [ (x_1, Type (unit/1)) ], Type (unit/1)),
                Match
                  (?,
                    Variable
                      (?,
                        x_1/0),
                    [
                      (Constructor
                        (tt/1),
                        Sequence
                          (49,
                            Apply
                              (49,
                                Variable
                                  (49,
                                    OCaml.Effect.State.write/1),
                                [
                                  Variable
                                    (49,
                                      b/0);
                                  Apply
                                    (49,
                                      Variable
                                        (49,
                                          OCaml.Effect.State.read/1),
                                      [
                                        Variable
                                          (49,
                                            b/0)
                                      ])
                                ]),
                            Apply
                              (50,
                                Variable
                                  (50,
                                    OCaml.Effect.State.write/1),
                                [
                                  Variable
                                    (50,
                                      str/0);
                                  Apply
                                    (50,
                                      Variable
                                        (50,
                                          String.append/1),
                                      [
                                        Constant
                                          (50,
                                            String("toggle "));
                                        Apply
                                          (50,
                                            Variable
                                              (50,
                                                OCaml.Effect.State.read/1),
                                            [
                                              Variable
                                                (50,
                                                  str/0)
                                            ])
                                      ])
                                ])))
                    ]))
            ]) in
        Sequence
          (51,
            Apply
              (51, Variable (51, update/0), [ Constructor (51, tt/1) ]),
            Sequence
              (52,
                Apply
                  (52, Variable (52, update/0),
                    [ Constructor (52, tt/1) ]),
                Sequence
                  (53,
                    Apply
                      (53, Variable (53, update/0),
                        [ Constructor (53, tt/1) ]),
                    Tuple
                      (54,
                        Apply
                          (54,
                            Variable
                              (54,
                                OCaml.Effect.State.read/1),
                            [ Variable (54, b/0) ]),
                        Apply
                          (54,
                            Variable
                              (54,
                                OCaml.Effect.State.read/1),
                            [ Variable (54, str/0) ]),
                        Apply
                          (54,
                            Variable
                              (54,
                                OCaml.Effect.State.read/1),
                            [ Variable (54, r/0) ]))))))
    ])

56
Value
  (non_rec, @.,
    [
      ((partials_test, [ ], [ (x, Type (unit/1)) ],
        Type (OCaml.Effect.State.t/1, Type (Z/1))),
        Match
          (?, Variable (?, x/0),
            [
              (Constructor (tt/1),
                LetFun 57
                  (non_rec, @.,
                    [
                      ((f1,
                        [
                        ],
                        [
                          (x,
                            Type
                              (OCaml.Effect.State.t/1,
                                Type
                                  (Z/1)));
                          (y,
                            Type
                              (Z/1))
                        ],
                        Type
                          (OCaml.Effect.State.t/1,
                            Type
                              (Z/1))),
                        Sequence
                          (58,
                            Apply
                              (58,
                                Variable
                                  (58,
                                    OCaml.Effect.State.write/1),
                                [
                                  Variable
                                    (58,
                                      x/0);
                                  Variable
                                    (58,
                                      y/0)
                                ]),
                            Variable
                              (59,
                                x/0)))
                    ])
                  in
                LetVar 60 f1_test =
                  Apply
                    (60,
                      Variable
                        (60,
                          f1/0),
                      [
                        Variable
                          (60,
                            r/0)
                      ])
                  in
                LetVar 61 f1_test =
                  Apply
                    (61,
                      Variable
                        (61,
                          f1_test/0),
                      [
                        Constant
                          (61,
                            Int(15))
                      ])
                  in
                LetFun 62
                  (non_rec, @.,
                    [
                      ((f2,
                        [
                        ],
                        [
                          (l1,
                            Type
                              (OCaml.Effect.State.t/1,
                                Type
                                  (list/1,
                                    Type
                                      (Z/1))));
                          (l2,
                            Type
                              (list/1,
                                Type
                                  (string/1)))
                        ],
                        Type
                          (OCaml.Effect.State.t/1,
                            Type
                              (Z/1))),
                        Apply
                          (63,
                            Variable
                              (63,
                                OCaml.Pervasives.ref/1),
                            [
                              Apply
                                (63,
                                  Variable
                                    (63,
                                      Z.add/1),
                                  [
                                    Apply
                                      (63,
                                        Variable
                                          (63,
                                            OCaml.List.length/-1),
                                        [
                                          Apply
                                            (63,
                                              Variable
                                                (63,
                                                  OCaml.Effect.State.read/1),
                                              [
                                                Variable
                                                  (63,
                                                    l1/0)
                                              ])
                                        ]);
                                    Apply
                                      (63,
                                        Variable
                                          (63,
                                            OCaml.List.length/-1),
                                        [
                                          Variable
                                            (63,
                                              l2/0)
                                        ])
                                  ])
                            ]))
                    ])
                  in
                LetVar 64 f2_test =
                  Apply
                    (64,
                      Variable
                        (64,
                          f2/0),
                      [
                        Apply
                          (64,
                            Variable
                              (64,
                                OCaml.Pervasives.ref/1),
                            [
                              Constructor
                                (64,
                                  cons/1,
                                  Constant
                                    (64,
                                      Int(1)),
                                  Constructor
                                    (64,
                                      cons/1,
                                      Constant
                                        (64,
                                          Int(2)),
                                      Constructor
                                        (64,
                                          cons/1,
                                          Constant
                                            (64,
                                              Int(3)),
                                          Constructor
                                            (64,
                                              []/1))))
                            ])
                      ])
                  in
                LetVar 65 f2_test =
                  Apply
                    (65,
                      Variable
                        (65,
                          f2_test/0),
                      [
                        Constructor
                          (65,
                            cons/1,
                            Constant
                              (65,
                                String("hi")),
                            Constructor
                              (65,
                                cons/1,
                                Constant
                                  (65,
                                    String("hey")),
                                Constructor
                                  (65,
                                    []/1)))
                      ])
                  in
                Apply
                  (66,
                    Variable
                      (66,
                        f1/0),
                    [
                      Variable
                        (66,
                          f2_test/0);
                      Apply
                        (66,
                          Variable
                            (66,
                              OCaml.Effect.State.read/1),
                          [
                            Variable
                              (66,
                                f1_test/0)
                          ])
                    ]))
            ]))
    ])

68
Value
  (non_rec, @.,
    [
      ((multiple_returns_test, [ ], [ (x, Type (unit/1)) ],
        (Type (Z/1) * Type (OCaml.Effect.State.t/1, Type (Z/1)))),
        Match
          (?, Variable (?, x/0),
            [
              (Constructor (tt/1),
                LetFun 69
                  (non_rec, @.,
                    [
                      ((f,
                        [
                        ],
                        [
                          (x,
                            Type
                              (OCaml.Effect.State.t/1,
                                Type
                                  (Z/1)));
                          (y,
                            Type
                              (Z/1))
                        ],
                        (Type
                          (Z/1)
                          ->
                          (Type
                            (OCaml.Effect.State.t/1,
                              Type
                                (Z/1))
                            ->
                            Type
                              (OCaml.Effect.State.t/1,
                                Type
                                  (Z/1))))),
                        Sequence
                          (70,
                            Apply
                              (70,
                                Variable
                                  (70,
                                    OCaml.Effect.State.write/1),
                                [
                                  Variable
                                    (70,
                                      x/0);
                                  Variable
                                    (70,
                                      y/0)
                                ]),
                            Function
                              (71,
                                z,
                                Sequence
                                  (71,
                                    Apply
                                      (72,
                                        Variable
                                          (72,
                                            OCaml.Effect.State.write/1),
                                        [
                                          Variable
                                            (72,
                                              x/0);
                                          Apply
                                            (72,
                                              Variable
                                                (72,
                                                  Z.add/1),
                                              [
                                                Apply
                                                  (72,
                                                    Variable
                                                      (72,
                                                        OCaml.Effect.State.read/1),
                                                    [
                                                      Variable
                                                        (72,
                                                          x/0)
                                                    ]);
                                                Variable
                                                  (72,
                                                    z/0)
                                              ])
                                        ]),
                                    Function
                                      (73,
                                        w,
                                        LetVar
                                          73
                                          tmp
                                          =
                                          Apply
                                            (74,
                                              Variable
                                                (74,
                                                  OCaml.Effect.State.read/1),
                                              [
                                                Variable
                                                  (74,
                                                    w/0)
                                              ])
                                          in
                                        Sequence
                                          (75,
                                            Apply
                                              (75,
                                                Variable
                                                  (75,
                                                    OCaml.Effect.State.write/1),
                                                [
                                                  Variable
                                                    (75,
                                                      w/0);
                                                  Apply
                                                    (75,
                                                      Variable
                                                        (75,
                                                          Z.mul/1),
                                                      [
                                                        Constant
                                                          (75,
                                                            Int(2));
                                                        Apply
                                                          (75,
                                                            Variable
                                                              (75,
                                                                OCaml.Effect.State.read/1),
                                                            [
                                                              Variable
                                                                (75,
                                                                  x/0)
                                                            ])
                                                      ])
                                                ]),
                                            Sequence
                                              (76,
                                                Apply
                                                  (76,
                                                    Variable
                                                      (76,
                                                        OCaml.Effect.State.write/1),
                                                    [
                                                      Variable
                                                        (76,
                                                          x/0);
                                                      Variable
                                                        (76,
                                                          tmp/0)
                                                    ]),
                                                Variable
                                                  (77,
                                                    x/0))))))))
                    ])
                  in
                LetVar 80 s =
                  Apply
                    (80,
                      Variable
                        (80,
                          OCaml.Pervasives.ref/1),
                      [
                        Constant
                          (80,
                            Int(110))
                      ])
                  in
                LetVar 81 f1 =
                  Apply
                    (81,
                      Variable
                        (81,
                          f/0),
                      [
                        Apply
                          (81,
                            Variable
                              (81,
                                OCaml.Pervasives.ref/1),
                            [
                              Constant
                                (81,
                                  Int(5))
                            ])
                      ])
                  in
                LetVar 82 f2 =
                  Apply
                    (82,
                      Variable
                        (82,
                          f1/0),
                      [
                        Constant
                          (82,
                            Int(2))
                      ])
                  in
                LetVar 83 f3 =
                  Apply
                    (83,
                      Variable
                        (83,
                          f2/0),
                      [
                        Constant
                          (83,
                            Int(7))
                      ])
                  in
                LetVar 84 f4 =
                  Apply
                    (84,
                      Variable
                        (84,
                          f3/0),
                      [
                        Variable
                          (84,
                            s/0)
                      ])
                  in
                Tuple
                  (85,
                    Apply
                      (85,
                        Variable
                          (85,
                            OCaml.Effect.State.read/1),
                        [
                          Variable
                            (85,
                              f4/0)
                        ]),
                    Variable
                      (85,
                        s/0)))
            ]))
    ])
