2
Value
  (non_rec, @.,
    [
      ((x, [ ], [ (a, Type (Z)); (b, Type (Z)) ], Type (Z)),
        LetVar 3 y =
          Apply
            (3, Variable (3, OCaml.Pervasives.ref),
              [ Constant (3, Int(0)) ]) in
        Sequence
          (4,
            For
              (4, i, true, Variable (4, a), Variable (4, b),
                Apply
                  (5, Variable (5, OCaml.Effect.State.write),
                    [
                      Variable (5, y);
                      Apply
                        (5,
                          Variable
                            (5,
                              Z.add),
                          [
                            Apply
                              (5,
                                Variable
                                  (5,
                                    OCaml.Effect.State.read),
                                [
                                  Variable
                                    (5,
                                      y)
                                ]);
                            Constant
                              (5,
                                Int(1))
                          ])
                    ])),
            Apply
              (7, Variable (7, OCaml.Effect.State.read),
                [ Variable (7, y) ])))
    ])

9
Value
  (non_rec, @.,
    [
      ((nested, [ ], [ (x, Type (Z)); (y, Type (Z)) ], Type (list, Type (bool))),
        LetVar 10 a =
          Apply
            (10, Variable (10, OCaml.Pervasives.ref),
              [ Constructor (10, []) ]) in
        Sequence
          (11,
            For
              (11, i, true, Constant (11, Int(0)), Variable (11, x),
                Sequence
                  (12,
                    For
                      (12, j, true, Constant (12, Int(0)),
                        Variable (12, y),
                        Apply
                          (13,
                            Variable
                              (13,
                                OCaml.Effect.State.write),
                            [
                              Variable (13, a);
                              Constructor
                                (13,
                                  cons,
                                  Constructor
                                    (13,
                                      true),
                                  Apply
                                    (13,
                                      Variable
                                        (13,
                                          OCaml.Effect.State.read),
                                      [
                                        Variable
                                          (13,
                                            a)
                                      ]))
                            ])),
                    Apply
                      (15,
                        Variable
                          (15, OCaml.Effect.State.write),
                        [
                          Variable (15, a);
                          Constructor
                            (15,
                              cons,
                              Constructor
                                (15,
                                  false),
                              Apply
                                (15,
                                  Variable
                                    (15,
                                      OCaml.Effect.State.read),
                                  [
                                    Variable
                                      (15,
                                        a)
                                  ]))
                        ]))),
            Apply
              (17, Variable (17, OCaml.Effect.State.read),
                [ Variable (17, a) ])))
    ])

19
Value
  (non_rec, @.,
    [
      ((raises, [ ], [ (x, Type (Z)) ], Type (unit)),
        For
          (20, i, true, Constant (20, Int(0)), Variable (20, x),
            Apply
              (21, Variable (21, OCaml.Pervasives.failwith),
                [ Constant (21, String("x is not less than 0")) ])))
    ])

24
Value
  (non_rec, @.,
    [
      ((argument_effects, [ ],
        [ (x, Type (OCaml.Effect.State.t, Type (Z))); (y, Type (Z)) ],
        Type (Z)),
        LetVar 25 y =
          Apply
            (25, Variable (25, OCaml.Pervasives.ref), [ Variable (25, y) ])
          in
        LetVar 26 z =
          Apply
            (26, Variable (26, OCaml.Pervasives.ref),
              [ Constant (26, Int(0)) ]) in
        Sequence
          (27,
            For
              (27, i, true, Constant (27, Int(0)),
                Apply
                  (27, Variable (27, OCaml.Effect.State.read),
                    [ Variable (27, x) ]),
                Sequence
                  (28,
                    For
                      (28, j, true, Constant (28, Int(0)),
                        Apply
                          (28,
                            Variable
                              (28,
                                OCaml.Effect.State.read),
                            [ Variable (28, y) ]),
                        Apply
                          (29,
                            Variable
                              (29,
                                OCaml.Effect.State.write),
                            [
                              Variable (29, z);
                              Apply
                                (29,
                                  Variable
                                    (29,
                                      Z.add),
                                  [
                                    Apply
                                      (29,
                                        Variable
                                          (29,
                                            OCaml.Effect.State.read),
                                        [
                                          Variable
                                            (29,
                                              z)
                                        ]);
                                    Constant
                                      (29,
                                        Int(1))
                                  ])
                            ])),
                    Apply
                      (31,
                        Variable
                          (31, OCaml.Effect.State.write),
                        [
                          Variable (31, y);
                          Apply
                            (31,
                              Variable
                                (31,
                                  Z.sub),
                              [
                                Apply
                                  (31,
                                    Variable
                                      (31,
                                        OCaml.Effect.State.read),
                                    [
                                      Variable
                                        (31,
                                          y)
                                    ]);
                                Constant
                                  (31,
                                    Int(1))
                              ])
                        ]))),
            Apply
              (33, Variable (33, OCaml.Effect.State.read),
                [ Variable (33, z) ])))
    ])
