3
Value
  (non_rec, @.,
    [
      ((temp, [ ], [ ], Type (unit)),
        Apply
          (3, Variable (3, OCaml/Pervasives.ignore),
            [
              Apply
                (3, Variable (3, Z.add),
                  [
                    Constant
                      (3,
                        Int(1));
                    Constant
                      (3,
                        Int(1))
                  ])
            ]))
    ])

5
Value
  (non_rec, @.,
    [
      ((temp_1, [ ], [ ], (Type (Z) * Type (string))),
        Tuple (5, Constant (5, Int(15)), Constant (5, String("hi"))))
    ])

5
Value
  (non_rec, @.,
    [
      ((a, [ ], [ ], Type (Z)),
        Match
          (?, Variable (?, Ex44/temp_1),
            [ (Tuple (a, b), Variable (?, Ex44/a)) ]))
    ])

5
Value
  (non_rec, @.,
    [
      ((b, [ ], [ ], Type (string)),
        Match
          (?, Variable (?, Ex44/temp_1),
            [ (Tuple (a, b), Variable (?, Ex44/b)) ]))
    ])

7
Inductive a (= a_1):
  ([ ], [ (A, [ Type (Z); Type (bool) ]) ])

9
Value
  (non_rec, @.,
    [
      ((temp_2, [ ], [ ], Type (Ex44/a_1)),
        Constructor (9, Ex44/A, Constant (9, Int(15)), Constructor (9, true)))
    ])

9
Value
  (non_rec, @.,
    [
      ((i, [ ], [ ], Type (Z)),
        Match
          (?, Variable (?, Ex44/temp_2),
            [ (Constructor (Ex44/A, i, j), Variable (?, Ex44/i)) ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((j, [ ], [ ], Type (bool)),
        Match
          (?, Variable (?, Ex44/temp_2),
            [ (Constructor (Ex44/A, i, j), Variable (?, Ex44/j)) ]))
    ])

11
Record b (= b_1):
  ([ ], [ (first, Type (Z)); (second, Type (bool)); (third, Type (string)) ])

13
Value
  (non_rec, @.,
    [
      ((b_val, [ ], [ ], Type (Ex44/b_1)),
        Record
          (13, None, (Ex44/first, Some Constant (13, Int(12))),
            (Ex44/second, Some Constructor (13, false)),
            (Ex44/third, Some Constant (13, String("hello")))))
    ])

15
Value
  (non_rec, @.,
    [
      ((hi, [ ], [ ], Type (Z)),
        Match
          (15, Variable (15, Ex44/b_val),
            [ (Record ((Ex44/first, hi)), Variable (15, Ex44/hi)) ]))
    ])

16
Value
  (non_rec, @.,
    [
      ((hey, [ ], [ ], Type (bool)),
        Match
          (16, Variable (16, Ex44/b_val),
            [ (Record ((Ex44/second, hey)), Variable (16, Ex44/hey)) ]))
    ])

17
Value
  (non_rec, @.,
    [ ((temp_5, [ ], [ ], Type (Ex44/b_1)), Variable (17, Ex44/b_val)) ])

17
Value
  (non_rec, @.,
    [
      ((hello, [ ], [ ], Type (string)),
        Match
          (?, Variable (?, Ex44/temp_5),
            [
              (Record
                ((Ex44/second, hey (= hey_1)),
                  (Ex44/third, hello)),
                Variable (?, Ex44/hello))
            ]))
    ])

17
Value
  (non_rec, @.,
    [
      ((hey (= hey_1), [ ], [ ], Type (bool)),
        Match
          (?, Variable (?, Ex44/temp_5),
            [
              (Record
                ((Ex44/second, hey (= hey_1)),
                  (Ex44/third, hello)),
                Variable (?, Ex44/hey_1))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((temp_6, [ ], [ ], Type (Ex44/b_1)), Variable (19, Ex44/b_val));
      ((temp_7, [ ], [ ], Type (Ex44/b_1)), Variable (20, Ex44/b_val));
      ((number1b, [ ], [ ], Type (Z)),
        Match
          (21, Variable (21, Ex44/b_val),
            [
              (Record ((Ex44/first, number1b)),
                Variable (21, Ex44/number1b))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((number1a, [ ], [ ], Type (Z)),
        Match
          (?, Variable (?, Ex44/temp_6),
            [
              (Record ((Ex44/first, number1a), (Ex44/second, number2a)),
                Variable (?, Ex44/number1a))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((number2a, [ ], [ ], Type (bool)),
        Match
          (?, Variable (?, Ex44/temp_6),
            [
              (Record ((Ex44/first, number1a), (Ex44/second, number2a)),
                Variable (?, Ex44/number2a))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((number2b, [ ], [ ], Type (bool)),
        Match
          (?, Variable (?, Ex44/temp_7),
            [
              (Record ((Ex44/second, number2b), (Ex44/third, number3)),
                Variable (?, Ex44/number2b))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((number3, [ ], [ ], Type (string)),
        Match
          (?, Variable (?, Ex44/temp_7),
            [
              (Record ((Ex44/second, number2b), (Ex44/third, number3)),
                Variable (?, Ex44/number3))
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((temp_9, [ ], [ ], Type (Ex44/b_1)),
        Record
          (24, None, (Ex44/first, Some Variable (24, Ex44/hi)),
            (Ex44/second, Some Variable (24, Ex44/hey_1)),
            (Ex44/third, Some Variable (24, Ex44/hello))))
    ])

23
Value
  (non_rec, @.,
    [
      ((first (= first_1), [ ], [ ], Type (Z)),
        Match
          (?, Variable (?, Ex44/temp_9),
            [
              (Record
                ((Ex44/first, first (= first_1)),
                  (Ex44/second,
                    second
                    (=
                    second_1)),
                  (Ex44/third,
                    third
                    (=
                    third_1))),
                Variable (?, Ex44/first_1))
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((second (= second_1), [ ], [ ], Type (bool)),
        Match
          (?, Variable (?, Ex44/temp_9),
            [
              (Record
                ((Ex44/first, first (= first_1)),
                  (Ex44/second,
                    second
                    (=
                    second_1)),
                  (Ex44/third,
                    third
                    (=
                    third_1))),
                Variable (?, Ex44/second_1))
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((third (= third_1), [ ], [ ], Type (string)),
        Match
          (?, Variable (?, Ex44/temp_9),
            [
              (Record
                ((Ex44/first, first (= first_1)),
                  (Ex44/second,
                    second
                    (=
                    second_1)),
                  (Ex44/third,
                    third
                    (=
                    third_1))),
                Variable (?, Ex44/third_1))
            ]))
    ])

26
Record c:
  ([ a ], [ (f, (a -> Type (Z))) ])

28
Value
  (non_rec, @.,
    [
      ((c_val, [ A ], [ ], Type (Ex44/c, A)),
        Record
          (28, None,
            (Ex44/f,
              Some
                Function
                  (28, x,
                    Match
                      (28, Variable (?, Ex44/x),
                        [ (Any, Constant (28, Int(12))) ])))))
    ])

30
Value
  (non_rec, @.,
    [
      ((f (= f_1), [ A ], [ ], (A -> Type (Z))),
        Match
          (30, Variable (30, Ex44/c_val),
            [ (Record ((Ex44/f, f (= f_1))), Variable (30, Ex44/f_1)) ]))
    ])

32
Inductive d:
  ([ a ], [ (F, [ (a -> Type (Z)) ]) ])

34
Value
  (non_rec, @.,
    [
      ((d_val, [ A ], [ ], Type (Ex44/d, A)),
        Constructor
          (34, Ex44/F,
            Function
              (34, x,
                Match
                  (34, Variable (?, Ex44/x),
                    [ (Any, Constant (34, Int(12))) ]))))
    ])

36
Value
  (non_rec, @.,
    [
      ((g, [ A ], [ ], (A -> Type (Z))),
        Match
          (36, Variable (36, Ex44/d_val),
            [ (Constructor (Ex44/F, g), Variable (36, Ex44/g)) ]))
    ])
